//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Comments = new HashSet<Comment>();
            this.Histories = new HashSet<History>();
            this.Questions = new HashSet<Question>();
            this.Documents = new HashSet<Document>();
            this.News = new HashSet<News>();
            this.Solutions = new HashSet<Solution>();
        }
    
        public int Id { get; set; }
        public int Type_Member_Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int Rank { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual Type_Member Type_Member { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<Solution> Solutions { get; set; }
    }
}
