//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string Content { get; set; }
        public string Image { get; set; }
        public int View { get; set; }
        public System.DateTime Created_Time { get; set; }
        public int Created_By { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
