//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
            this.Comments = new HashSet<Comment>();
            this.Histories = new HashSet<History>();
            this.Solutions = new HashSet<Solution>();
            this.Rate_Document = new HashSet<Rate_Document>();
            this.Rate_Question = new HashSet<Rate_Question>();
        }
    
        public int Id { get; set; }
        public int Subject_Id { get; set; }
        public int Topic_Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public int Created_By { get; set; }
        public System.DateTime Created_Time { get; set; }
        public Nullable<int> Rank_Id { get; set; }
        public Nullable<int> View { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<History> Histories { get; set; }
        public virtual Member Member { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual ICollection<Solution> Solutions { get; set; }
        public virtual ICollection<Rate_Document> Rate_Document { get; set; }
        public virtual ICollection<Rate_Question> Rate_Question { get; set; }
        public virtual Rank Rank1 { get; set; }
    }
}
