//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate_Document
    {
        public int Member_Id { get; set; }
        public int Document_Id { get; set; }
        public int Rate { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Question Question { get; set; }
    }
}
