//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Member
    {
        public Type_Member()
        {
            this.Members = new HashSet<Member>();
            this.Role_Member = new HashSet<Role_Member>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<Role_Member> Role_Member { get; set; }
    }
}
